version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seeding.sql:/docker-entrypoint-initdb.d/seeding.sql

  php:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php